version: "3.9"

services:
    redis:
        image: redis:alpine
        container_name: livekit-redis
        ports:
            - 6379:6379
        volumes:
            - ./volumes/redis:/data
        command: redis-server --appendonly yes

    egress:
        image: livekit/egress
        container_name: livekit-egress
        depends_on:
            - redis
        environment:
            EGRESS_CONFIG_FILE: /out/egress_config.yaml
            LOG_LEVEL: debug
        volumes:
            - ./volumes/egress:/out/
        ports:
            - 7980:7980
        cap_add:
            - SYS_ADMIN

    livekit:
        image: livekit/livekit-server
        container_name: livekit-server
        depends_on:
            - redis
        ports:
            - 7880:7880
            - 7881:7881
            - 7882:7882/udp
        volumes: 
            - ./volumes/livekit/livekit_config.yaml:/livekit_config.yaml
        command: --config /livekit_config.yaml --node-ip 172.17.0.1