log_level: debug
api_key: devkey
api_secret: secret
ws_url: ws://172.17.0.1:7880
insecure: true
redis:
    address: redis:6379
# s3:
#     access_key: ""
#     secret: ""
#     region: us-east-1
#     bucket: video-conference-livekit-egress
backup_storage: /home/egress
